Slight refactoring
masaner/sfdx-hardis pull request #1
Opened 2024-05-13 20:40 UTC by nvuillam

Please can you merge in your main branch, then create a sub branch, then check it's all ok for you, then create a new PR to the master repo ? :)

I've not tested my refactos so still a little bit of rework probably

Sorry for the mess ^^

2024-05-13 21:32 UTC, nvuillam commented
@masaner I think it's ok now, you can merge then make a PR if it's ok for you too :)

2024-05-14 09:28 UTC, masaner requested changes

2024-05-14 09:28 UTC, masaner commented on src/commands/hardis/org/diagnose/unusedusers.ts
> +      `(CreatedDate != LAST_N_DAYS:${this.lastNdays} AND LastLoginDate == NULL)` + // Check also for users never used
Should this query be updated? 

FROM: AND LastLoginDate == NULL
TO: AND LastLoginDate = NULL

2024-05-14 09:29 UTC, masaner commented on src/commands/hardis/org/diagnose/unusedusers.ts
> +      `(CreatedDate < LAST_N_DAYS:${this.lastNdays} AND LastLoginDate = NULL)` + // Check also for users never used
Oh, nvm, i see its changed here.

2024-05-14 09:29 UTC, masaner approved these changes
Looks good!

2024-05-14 09:30 UTC, merged